(() => {
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d'),mode=document.body.dataset.game;
const W=900,H=560; canvas.width=W;canvas.height=H;
const cfg={robot:{title:'ROBOT ARENA',sub:'Survive the machine uprising.',help:'WASD / arrows move · click or SPACE fire'},island:{title:'ISLAND SURVIVOR',sub:'Gather supplies and build a camp before the storm.',help:'WASD move · click resources · B build camp'},space:{title:'SPACE MINER',sub:'Mine asteroids, collect crystals, and outrun pirates.',help:'WASD / arrows steer · SPACE fire'},tower:{title:'TOWER DEFENDER',sub:'Place defenders and protect the crystal.',help:'Click empty ground to place towers · towers fire automatically'},farm:{title:'FARM RUSH',sub:'Grow crops and complete timed orders.',help:'Click soil to plant · click ripe crops to harvest'},dungeon:{title:'DUNGEON ESCAPE',sub:'Find the key and reach the exit.',help:'WASD / arrows move through the dungeon'},city:{title:'CITY BUILDER',sub:'Turn empty land into a thriving city.',help:'Click tiles to build · earn coins from happy citizens'},ocean:{title:'OCEAN EXPLORER',sub:'Dive for treasure before your oxygen runs out.',help:'WASD / arrows swim · collect treasure · return to buoy'},racing:{title:'RACING RIVALS',sub:'Dodge traffic and own the highway.',help:'A/D or arrows steer · SPACE boost'},ninja:{title:'NINJA RUN',sub:'Run, leap, and collect the ancient coins.',help:'SPACE / click jump · survive as long as possible'}}[mode]||{title:'ARCADE GAME',sub:'Have fun!',help:'Use the keyboard or touch controls'};
document.title=cfg.title;document.querySelector('h1').textContent=cfg.title;document.getElementById('subtitle').textContent=cfg.sub;document.querySelector('.help').innerHTML=cfg.help+' <span class="touch-hint">· touch supported</span>';
const keys={},pointer={x:W/2,y:H/2,down:false};let touchStart=null,raf,last=0,message='',messageTime=0;
const S={score:0,level:1,lives:3,time:0,over:false,won:false,mode:{}};
function resize(){const r=canvas.getBoundingClientRect();canvas.width=W;canvas.height=H;ctx.setTransform(1,0,0,1,0,0)}addEventListener('resize',resize);
function reset(){S.score=0;S.level=1;S.lives=3;S.time=0;S.over=false;S.won=false;S.mode={};initMode();document.getElementById('modal').hidden=true;syncHud();}
function msg(t){message=t;messageTime=2}
function score(n){S.score+=n;syncHud()}
function syncHud(){document.getElementById('score').textContent=S.score;document.getElementById('level').textContent=S.level;document.getElementById('lives').textContent=S.lives}
function end(win=false){S.over=true;S.won=win;document.getElementById('modal-title').textContent=win?'You Win!':'Game Over';document.getElementById('modal-text').textContent=win?`Great run! Score: ${S.score}`:`Final score: ${S.score}. Try again!`;document.getElementById('modal').hidden=false}
function pos(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height}}
addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(e.code==='Space')e.preventDefault()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
canvas.addEventListener('mousemove',e=>Object.assign(pointer,pos(e)));canvas.addEventListener('mousedown',e=>{Object.assign(pointer,pos(e));pointer.down=true;clickMode()});addEventListener('mouseup',()=>pointer.down=false);
canvas.addEventListener('touchstart',e=>{e.preventDefault();touchStart=pos(e.touches[0]);Object.assign(pointer,touchStart);pointer.down=true;clickMode()},{passive:false});canvas.addEventListener('touchmove',e=>{e.preventDefault();Object.assign(pointer,pos(e.touches[0]))},{passive:false});canvas.addEventListener('touchend',e=>{e.preventDefault();pointer.down=false;touchStart=null},{passive:false});
document.getElementById('restart').onclick=reset;
function text(t,x,y,size=18,color='#fff',align='center'){ctx.fillStyle=color;ctx.font=`700 ${size}px Segoe UI`;ctx.textAlign=align;ctx.fillText(t,x,y)}function rect(x,y,w,h,c,r=0){ctx.fillStyle=c;if(r){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill()}else ctx.fillRect(x,y,w,h)}function circle(x,y,r,c){ctx.fillStyle=c;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill()}function clamp(v,a,b){return Math.max(a,Math.min(b,v))}function bg(c='#14253a'){rect(0,0,W,H,c)}function moveObj(o,dt,s=140){let dx=0,dy=0;if(keys.w||keys.arrowup)dy--;if(keys.s||keys.arrowdown)dy++;if(keys.a||keys.arrowleft)dx--;if(keys.d||keys.arrowright)dx++;if(dx||dy){const l=Math.hypot(dx,dy);o.x+=dx/l*s*dt;o.y+=dy/l*s*dt}o.x=clamp(o.x,18,W-18);o.y=clamp(o.y,40,H-18)}
function initMode(){if(mode==='robot')return robotInit();if(mode==='island')return islandInit();if(mode==='space')return spaceInit();if(mode==='tower')return towerInit();if(mode==='farm')return farmInit();if(mode==='dungeon')return dungeonInit();if(mode==='city')return cityInit();if(mode==='ocean')return oceanInit();if(mode==='racing')return racingInit();if(mode==='ninja')return ninjaInit()}
function clickMode(){if(S.over)return;if(mode==='robot')robotClick();if(mode==='island')islandClick();if(mode==='tower')towerClick();if(mode==='farm')farmClick();if(mode==='city')cityClick();if(mode==='ocean')oceanClick();if(mode==='ninja'&&pointer.down)S.mode.p.y=420,S.mode.p.v=-430}
function update(dt){S.time+=dt;if(mode==='robot')robotUpdate(dt);if(mode==='island')islandUpdate(dt);if(mode==='space')spaceUpdate(dt);if(mode==='tower')towerUpdate(dt);if(mode==='farm')farmUpdate(dt);if(mode==='dungeon')dungeonUpdate(dt);if(mode==='city')cityUpdate(dt);if(mode==='ocean')oceanUpdate(dt);if(mode==='racing')racingUpdate(dt);if(mode==='ninja')ninjaUpdate(dt);if(messageTime>0)messageTime-=dt;syncHud()}
function draw(){if(mode==='robot')robotDraw();if(mode==='island')islandDraw();if(mode==='space')spaceDraw();if(mode==='tower')towerDraw();if(mode==='farm')farmDraw();if(mode==='dungeon')dungeonDraw();if(mode==='city')cityDraw();if(mode==='ocean')oceanDraw();if(mode==='racing')racingDraw();if(mode==='ninja')ninjaDraw();if(messageTime>0)text(message, W/2,42,16,'#ffe9a6');}

// ROBOT ARENA
function robotInit(){const m=S.mode;m.p={x:450,y:280};m.b=[];m.e=[];m.t=0;m.cool=0;m.spawn=0}function robotClick(){if(mode!=='robot')return;let m=S.mode;if(m.cool>0)return;const a=Math.atan2(pointer.y-m.p.y,pointer.x-m.p.x);m.b.push({x:m.p.x,y:m.p.y,vx:Math.cos(a)*430,vy:Math.sin(a)*430});m.cool=.18}function robotUpdate(dt){const m=S.mode;moveObj(m.p,dt,190);m.t+=dt;m.cool-=dt;m.spawn-=dt;if(m.spawn<=0){const side=Math.floor(Math.random()*4),p=side===0?{x:-20,y:Math.random()*H}:side===1?{x:W+20,y:Math.random()*H}:side===2?{x:Math.random()*W,y:-20}:{x:Math.random()*W,y:H+20};m.e.push({...p,v:50+S.level*5,hp:1});m.spawn=Math.max(.35,1.2-S.level*.08)}for(const b of m.b){b.x+=b.vx*dt;b.y+=b.vy*dt}m.b=m.b.filter(b=>b.x>-30&&b.x<W+30&&b.y>-30&&b.y<H+30);for(let i=m.e.length-1;i>=0;i--){const e=m.e[i],a=Math.atan2(m.p.y-e.y,m.p.x-e.x);e.x+=Math.cos(a)*e.v*dt;e.y+=Math.sin(a)*e.v*dt;for(let j=m.b.length-1;j>=0;j--)if(Math.hypot(e.x-m.b[j].x,e.y-m.b[j].y)<20){m.e.splice(i,1);m.b.splice(j,1);score(10);break}if(Math.hypot(e.x-m.p.x,e.y-m.p.y)<23){S.lives--;m.e.splice(i,1);if(!S.lives)end()}}if(Math.floor(S.time/15)+1>S.level){S.level++;msg('Robot wave upgraded!')}}function robotDraw(){bg('#111b31');for(let i=0;i<35;i++)circle((i*127)%W,(i*71)%H,2,'#30415d');const m=S.mode;for(const e of m.e){circle(e.x,e.y,17,'#d84c63');circle(e.x-6,e.y-3,3,'#fff');circle(e.x+6,e.y-3,3,'#fff')}for(const b of m.b){circle(b.x,b.y,5,'#ffe08a')}circle(m.p.x,m.p.y,19,'#70e0b1');rect(m.p.x-11,m.p.y-6,22,12,'#203c4b',3);text('●',m.p.x,m.p.y+6,15,'#eafff6')}

// ISLAND SURVIVOR
function islandInit(){const m=S.mode;m.p={x:450,y:280};m.items=[];m.wood=0;m.food=0;m.camp=false;for(let i=0;i<15;i++)m.items.push({x:40+Math.random()*820,y:90+Math.random()*400,type:Math.random()<.55?'tree':'berry',got:false})}function islandClick(){const m=S.mode;for(const o of m.items)if(!o.got&&Math.hypot(o.x-m.p.x,o.y-m.p.y)<45&&Math.hypot(o.x-pointer.x,o.y-pointer.y)<55){o.got=true;o.type==='tree'?m.wood++:m.food++;score(5);msg(o.type==='tree'?'+1 wood':'+1 food')}}function islandUpdate(dt){const m=S.mode;moveObj(m.p,dt,145);if(keys.b&&!m.camp&&m.wood>=5){m.wood-=5;m.camp=true;score(50);msg('Camp built! You survived the island.')}if(S.time>75&&!m.camp)end();if(S.time>75&&m.camp)end(true);if(Math.floor(S.time/15)+1>S.level)S.level++}function islandDraw(){bg('#4fc3d4');rect(18,65,864,475,'#d6ba72',22);for(const o of S.mode.items)if(!o.got){circle(o.x,o.y,22,o.type==='tree'?'#28794f':'#b83e5b');if(o.type==='tree')rect(o.x-4,o.y,8,24,'#75462a')}const p=S.mode.p;circle(p.x,p.y,15,'#f5f0c9');text('🌴 ISLAND',450,35,18,'#fff');text(`Wood ${S.mode.wood} · Food ${S.mode.food}${S.mode.camp?' · CAMP READY':''}`,450,525,16,'#173044')}

// SPACE MINER
function spaceInit(){const m=S.mode;m.p={x:450,y:470};m.a=[];m.b=[];m.t=0;m.cool=0;for(let i=0;i<12;i++)m.a.push({x:30+Math.random()*840,y:90+Math.random()*280,r:12+Math.random()*20,vx:(Math.random()-.5)*50,vy:(Math.random()-.5)*50})}function spaceClick(){if(S.mode.cool<=0){const m=S.mode;m.b.push({x:m.p.x,y:m.p.y-16,vx:0,vy:-430});m.cool=.25}}function spaceUpdate(dt){const m=S.mode;moveObj(m.p,dt,220);m.cool-=dt;if(keys[' '])spaceClick();for(const b of m.b)b.y+=b.vy*dt;m.b=m.b.filter(b=>b.y>-30);for(const a of m.a){a.x+=a.vx*dt;a.y+=a.vy*dt;if(a.x<10||a.x>890)a.vx*=-1;if(a.y<60||a.y>510)a.vy*=-1}for(let i=m.a.length-1;i>=0;i--)for(let j=m.b.length-1;j>=0;j--)if(Math.hypot(m.a[i].x-m.b[j].x,m.a[i].y-m.b[j].y)<m.a[i].r+6){score(15);m.a[i]={x:Math.random()*850+25,y:80,r:12+Math.random()*20,vx:(Math.random()-.5)*50,vy:30};m.b.splice(j,1);break}for(const a of m.a)if(Math.hypot(a.x-m.p.x,a.y-m.p.y)<a.r+17){S.lives--;a.y=40;if(!S.lives)end()}if(S.time>60)end(true)}function spaceDraw(){bg('#080e22');for(let i=0;i<80;i++)circle((i*79)%W,(i*43)%H,1.5,'#cfe9ff');for(const a of S.mode.a){circle(a.x,a.y,a.r,'#7a879a');circle(a.x-a.r*.3,a.y-a.r*.3,a.r*.25,'#4a5568')}for(const b of S.mode.b)rect(b.x-3,b.y-12,6,18,'#ffe07b');const p=S.mode.p;ctx.fillStyle='#70e0b1';ctx.beginPath();ctx.moveTo(p.x,p.y-22);ctx.lineTo(p.x-17,p.y+18);ctx.lineTo(p.x,p.y+10);ctx.lineTo(p.x+17,p.y+18);ctx.closePath();ctx.fill();text('CRYSTAL BELT',450,38,18,'#dbe8ff')}

// TOWER DEFENDER
function towerInit(){const m=S.mode;m.gold=100;m.en=[];m.towers=[];m.spawn=0;m.base=10;m.path=[{x:30,y:280},{x:230,y:280},{x:230,y:130},{x:500,y:130},{x:500,y:400},{x:870,y:400}]}function towerClick(){const m=S.mode,x=Math.round(pointer.x/40)*40,y=Math.round(pointer.y/40)*40;if(m.gold>=25&&!m.towers.some(t=>Math.hypot(t.x-x,t.y-y)<30)&&!m.path.some(p=>Math.hypot(p.x-x,p.y-y)<35)){m.towers.push({x,y,cool:0});m.gold-=25;msg('Tower placed')}}function towerUpdate(dt){const m=S.mode;m.spawn-=dt;if(m.spawn<=0){m.en.push({x:m.path[0].x,y:m.path[0].y,i:0,hp:30+S.level*8});m.spawn=Math.max(.55,1.6-S.level*.06)}for(const e of m.en){const target=m.path[e.i+1];if(!target)continue;const a=Math.atan2(target.y-e.y,target.x-e.x);e.x+=Math.cos(a)*(35+S.level*4)*dt;e.y+=Math.sin(a)*(35+S.level*4)*dt;if(Math.hypot(target.x-e.x,target.y-e.y)<5)e.i++;if(e.i>=m.path.length-1){m.base--;e.hp=0}}m.en=m.en.filter(e=>e.hp>0);for(const t of m.towers){t.cool-=dt;if(t.cool>0)continue;const e=m.en.find(e=>Math.hypot(e.x-t.x,e.y-t.y)<145);if(e){e.hp-=18;t.cool=.65;score(5);if(e.hp<=0)m.gold+=12}}if(m.base<=0)end();if(S.time>75)end(true);if(Math.floor(S.time/12)+1>S.level)S.level++}function towerDraw(){bg('#1d3b2b');for(let i=0;i<mPath().length-1;i++){const a=S.mode.path[i],b=S.mode.path[i+1];ctx.strokeStyle='#b98d59';ctx.lineWidth=30;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}for(const t of S.mode.towers){circle(t.x,t.y,18,'#70e0b1');circle(t.x,t.y,8,'#183b42')}for(const e of S.mode.en){circle(e.x,e.y,12,'#d84c63');ctx.fillStyle='#222';ctx.fillRect(e.x-15,e.y-22,30,4);ctx.fillStyle='#71e06b';ctx.fillRect(e.x-15,e.y-22,30*Math.max(0,e.hp/(30+S.level*8)),4)}text(`BASE ${S.mode.base} · GOLD ${S.mode.gold}`,450,38,18,'#fff')}function mPath(){return S.mode.path}

// FARM RUSH
function farmInit(){const m=S.mode;m.money=40;m.grid=[];m.order=3;for(let y=0;y<3;y++)for(let x=0;x<5;x++)m.grid.push({x,y,stage:0,t:0})}function farmClick(){const m=S.mode,x=Math.floor((pointer.x-210)/100),y=Math.floor((pointer.y-100)/100),c=m.grid.find(c=>c.x===x&&c.y===y);if(!c)return;if(c.stage===0&&m.money>=5){m.money-=5;c.stage=1;c.t=0;msg('Crop planted')}else if(c.stage===2){m.money+=15;score(20);c.stage=0;msg('Harvest sold!')}}function farmUpdate(dt){const m=S.mode;for(const c of m.grid)if(c.stage===1){c.t+=dt;if(c.t>3)c.stage=2}if(m.money>=200)end(true);if(S.time>90)end(m.money>=100);if(Math.floor(S.time/20)+1>S.level)S.level++}function farmDraw(){bg('#87c96b');text('FARM RUSH',450,42,22,'#fff');for(const c of S.mode.grid){const x=210+c.x*100,y=100+c.y*100;rect(x,y,80,80,'#805334',8);if(c.stage===1){circle(x+40,y+40,13,'#81c94b');text('·',x+40,y+43,23,'#d9f5a4')}if(c.stage===2){circle(x+40,y+40,20,'#f6c84b');text('✦',x+40,y+47,20,'#fff')}}text(`Coins ${S.mode.money} · Goal: 200`,450,475,18,'#173b24')}

// DUNGEON ESCAPE
function dungeonInit(){const m=S.mode;m.p={x:70,y:70};m.key=false;m.en=[{x:420,y:170},{x:700,y:420}];m.exit={x:820,y:480};m.walls=[];for(let i=0;i<10;i++)m.walls.push({x:100+((i*73)%650),y:100+((i*113)%360),w:80,h:18})}function dungeonUpdate(dt){const m=S.mode;moveObj(m.p,dt,150);for(const w of m.walls)if(m.p.x>w.x-15&&m.p.x<w.x+w.w+15&&m.p.y>w.y-15&&m.p.y<w.y+w.h+15){if(keys.a||keys.arrowleft)m.p.x+=5;if(keys.d||keys.arrowright)m.p.x-=5;if(keys.w||keys.arrowup)m.p.y+=5;if(keys.s||keys.arrowdown)m.p.y-=5}for(const e of m.en){const a=Math.atan2(m.p.y-e.y,m.p.x-e.x);e.x+=Math.cos(a)*35*dt;e.y+=Math.sin(a)*35*dt;if(Math.hypot(e.x-m.p.x,e.y-m.p.y)<20){S.lives--;e.x=700+Math.random()*100;e.y=100+Math.random()*350;if(!S.lives)end()}}if(!m.key&&Math.hypot(m.p.x-550,m.p.y-300)<28){m.key=true;score(50);msg('You found the key!')}if(m.key&&Math.hypot(m.p.x-m.exit.x,m.p.y-m.exit.y)<30)end(true)}function dungeonDraw(){bg('#19182d');for(const w of S.mode.walls)rect(w.x,w.y,w.w,w.h,'#4b4b6b',4);circle(550,300,16,S.mode.key?'#333':'#ffd45b');circle(S.mode.exit.x,S.mode.exit.y,23,S.mode.key?'#70e0b1':'#754b88');for(const e of S.mode.en)circle(e.x,e.y,16,'#d84c63');circle(S.mode.p.x,S.mode.p.y,14,'#e7c986');text(S.mode.key?'KEY FOUND · REACH THE EXIT':'FIND THE GOLDEN KEY',450,40,18,'#fff')}

// CITY BUILDER
function cityInit(){const m=S.mode;m.money=200;m.happy=0;m.tiles=[];for(let y=0;y<5;y++)for(let x=0;x<7;x++)m.tiles.push({x,y,type:'empty'})}function cityClick(){const m=S.mode,x=Math.floor((pointer.x-170)/80),y=Math.floor((pointer.y-90)/80),t=m.tiles.find(t=>t.x===x&&t.y===y);if(!t||t.type!=='empty')return;const types=[['house',40,2],['shop',70,4],['park',30,5]],choice=types[m.tiles.filter(a=>a.type!=='empty').length%3];if(m.money>=choice[1]){t.type=choice[0];m.money-=choice[1];m.happy+=choice[2];score(choice[2]*5);msg(`${choice[0]} built`)}}function cityUpdate(){const m=S.mode;if(m.happy>=60)end(true);if(m.money<=0&&m.tiles.every(t=>t.type!=='empty'))end(m.happy>=35);if(Math.floor(S.time/18)+1>S.level)S.level++}function cityDraw(){bg('#a2c5d8');for(const t of S.mode.tiles){const x=170+t.x*80,y=90+t.y*80;rect(x,y,64,64,t.type==='empty'?'#75949c':t.type==='house'?'#e09a63':t.type==='shop'?'#7587db':'#67b875',7);text(t.type==='empty'?'＋':t.type==='house'?'⌂':t.type==='shop'?'$':'✿',x+32,y+40,25,'#fff')}text(`Coins ${S.mode.money} · Happiness ${S.mode.happy}/60`,450,525,18,'#173244')}

// OCEAN EXPLORER
function oceanInit(){const m=S.mode;m.p={x:450,y:280};m.o2=100;m.treasures=[];m.buoy={x:450,y:90};for(let i=0;i<9;i++)m.treasures.push({x:60+Math.random()*780,y:140+Math.random()*370,got:false})}function oceanClick(){const m=S.mode;for(const t of m.treasures)if(!t.got&&Math.hypot(t.x-m.p.x,t.y-m.p.y)<45){t.got=true;score(25);msg('Treasure recovered!')}}function oceanUpdate(dt){const m=S.mode;moveObj(m.p,dt,125);m.o2-=dt*2.2;if(Math.hypot(m.p.x-m.buoy.x,m.p.y-m.buoy.y)<35)m.o2=Math.min(100,m.o2+dt*12);if(m.o2<=0)end();if(m.treasures.every(t=>t.got))end(true)}function oceanDraw(){bg('#167a9e');for(let i=0;i<12;i++){ctx.strokeStyle='#42aaca';ctx.lineWidth=2;ctx.beginPath();ctx.arc(70+i*76,100+(i%3)*140,35,0,Math.PI*2);ctx.stroke()}circle(S.mode.buoy.x,S.mode.buoy.y,23,'#ff7165');for(const t of S.mode.treasures)if(!t.got){rect(t.x-12,t.y-10,24,20,'#e8b94c',4);circle(t.x,t.y,5,'#fff')}circle(S.mode.p.x,S.mode.p.y,16,'#d9f3ff');text(`OXYGEN ${Math.ceil(S.mode.o2)}% · TREASURE ${S.mode.treasures.filter(t=>t.got).length}/9`,450,40,18,'#fff')}

// RACING RIVALS
function racingInit(){const m=S.mode;m.p={x:450,y:460};m.cars=[];m.distance=0;m.spawn=0;m.boost=100}function racingUpdate(dt){const m=S.mode;let dx=0;if(keys.a||keys.arrowleft)dx--;if(keys.d||keys.arrowright)dx++;m.p.x=clamp(m.p.x+dx*260*dt,300,600);const boost=(keys[' ']&&m.boost>0)?1.8:1;m.boost=clamp(m.boost+(keys[' ']?-20:12)*dt,0,100);m.distance+=dt*120*boost;m.spawn-=dt;if(m.spawn<=0){m.cars.push({x:300+Math.random()*300,y:-30,s:110+Math.random()*80});m.spawn=.8}for(const c of m.cars)c.y+=c.s*dt*boost;m.cars=m.cars.filter(c=>c.y<H+40);for(const c of m.cars)if(Math.abs(c.x-m.p.x)<35&&Math.abs(c.y-m.p.y)<45){S.lives--;c.y=H+50;if(!S.lives)end()}score(Math.floor(dt*2));if(m.distance>3000)end(true);if(Math.floor(m.distance/500)+1>S.level)S.level++}function racingDraw(){bg('#39424c');rect(270,0,360,H,'#20262d');for(let y=-20;y<H;y+=80)rect(445,y+(S.mode.distance%80),10,45,'#d7d7be');for(const c of S.mode.cars){rect(c.x-22,c.y-30,44,60,'#d84c63',8);circle(c.x-12,c.y-18,6,'#222');circle(c.x+12,c.y-18,6,'#222')}rect(S.mode.p.x-24,S.mode.p.y-32,48,64,'#70e0b1',8);text(`DISTANCE ${Math.floor(S.mode.distance)}m · BOOST ${Math.ceil(S.mode.boost)}%`,450,38,18,'#fff')}

// NINJA RUN
function ninjaInit(){const m=S.mode;m.p={x:140,y:420,v:0};m.obs=[];m.coins=[];m.spawn=0;m.speed=260}function ninjaUpdate(dt){const m=S.mode;m.p.v+=1000*dt;m.p.y+=m.p.v*dt;if(m.p.y>420){m.p.y=420;m.p.v=0}m.spawn-=dt;if(m.spawn<=0){m.obs.push({x:930,y:430,w:25,h:35});if(Math.random()<.7)m.coins.push({x:930,y:330-Math.random()*100});m.spawn=.9-Math.min(.35,S.time*.004)}for(const o of m.obs)o.x-=m.speed*dt;for(const c of m.coins)c.x-=m.speed*dt;m.obs=m.obs.filter(o=>o.x>-40);m.coins=m.coins.filter(c=>c.x>-30);for(const o of m.obs)if(o.x<m.p.x+15&&o.x+o.w>m.p.x-15&&m.p.y+4>o.y)end();for(let i=m.coins.length-1;i>=0;i--)if(Math.hypot(m.coins[i].x-m.p.x,m.coins[i].y-m.p.y)<28){score(10);m.coins.splice(i,1)}score(Math.floor(dt*3));if(S.time>60)end(true);if(Math.floor(S.time/12)+1>S.level){S.level++;m.speed+=25}}function ninjaDraw(){bg('#253555');rect(0,455,W,105,'#18233b');for(let i=0;i<8;i++)circle(80+i*130,110+(i%2)*35,28,'#344873');for(const o of S.mode.obs)rect(o.x,o.y,o.w,35,'#d45f4b',5);for(const c of S.mode.coins)circle(c.x,c.y,10,'#ffd45c');circle(S.mode.p.x,S.mode.p.y,17,'#e6f1ff');rect(S.mode.p.x-16,S.mode.p.y-5,32,8,'#d44d70');text(`RUN ${Math.floor(S.time)}s`,450,40,18,'#fff')}

function loop(now){raf=requestAnimationFrame(loop);const dt=Math.min(.05,(now-last)/1000||0);last=now;if(!S.over){update(dt);draw()}}reset();loop(performance.now());
})();
